woowa-techcamp-2022/android-banchan-10

app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/themes.xml
=> [CHORE] font style, theme 추가

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/common/TabName.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/MainActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/sidedish/SideDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/soupdish/SoupDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/utils/TabViewPagerAdapter.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_exhibition.xml, app/src/main/res/layout/fragment_maindish.xml, app/src/main/res/layout/fragment_sidedish.xml, app/src/main/res/layout/fragment_soupdish.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
=> [FEAT] MainActivity TabLayout 추가

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/recently/RecentlyViewedProductActivity.kt, app/src/main/res/drawable/ic_left_arrow.xml, app/src/main/res/layout/activity_recently_viewed_product.xml, app/src/main/res/layout/layout_app_bar_with_back_btn.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
=> [Feat] #11 recently_viewed_product화면 제작

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/model/DishItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishItemRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDishItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetSoupDishesUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/UiState.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/soupdish/SoupDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/soupdish/adapter/SoupAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/viewmodel/DishViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/utils/converter/BindingAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/utils/di/DishApiModule.kt, app/src/main/res/layout/fragment_soupdish.xml, app/src/main/res/layout/item_soup.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/themes.xml, buildSrc/src/main/kotlin/woowahan/android10/deliverbanchan/Dependencies.kt
* Retrofit Interceptor 주입 오류 해결
* 추가적인 내용 Issue에 명시하
=> [FEAT] #19 뜨끈한 국물 요리 화면 개발

app/build.gradle, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDishItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/bottomsheet/CartBottomSheetFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/bottomsheet/CartBottomSheetViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/maindish/MainDishFragment.kt, app/src/main/res/drawable/bg_cart_bottom_sheet.xml, app/src/main/res/drawable/btn_minus_32dp.xml, app/src/main/res/drawable/btn_plus_32dp.xml, app/src/main/res/drawable/ic_minus.xml, app/src/main/res/drawable/ic_minus_bottom_sheet.xml, app/src/main/res/drawable/ic_plus.xml, app/src/main/res/drawable/ic_plus_bottom_sheet.xml, app/src/main/res/layout/fragment_cart_bottom_sheet.xml, app/src/main/res/values/themes.xml
- 상품 리스트에서 카트 아이콘 누를 시 Bottom Sheet 나타남 (현재는 메인 탭 에서만)
- 선택한 상품 정보 나타내도록 구현
- @Parcelize 사용 (data class 객체 전달 시)
=> [FEAT] Cart Bottom Sheet 구현

.idea/deploymentTargetDropDown.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateEmptyUiDishItemUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetSoupDishesUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/base/BaseFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/MainActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/soupdish/SoupDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/view/CustomSortingSpinner.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/view/adapter/SortSpinnerAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/view/model/SortSpinnerItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/view/model/UiState.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/viewmodel/DishViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/utils/DishItemBindingAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/utils/converter/ConvertUitls.kt, app/src/main/res/drawable/bg_sort_spinner_down.xml, app/src/main/res/drawable/bg_sort_spinner_pop_up.xml, app/src/main/res/drawable/bg_sort_spinner_up.xml, app/src/main/res/drawable/ic_sorted_spinner_selected.xml, app/src/main/res/drawable/ic_up.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_soupdish.xml, app/src/main/res/layout/item_sort_spinner_drop_down.xml, app/src/main/res/layout/item_sort_spinner_selected.xml, app/src/main/res/values/strings.xml
* 스피너 셀렉트 포지션 상태에 따른 리스트 소팅 구현
* 메인화면 앱바 Layout 변경
=> [FEAT] 리스트 소팅 가능한 스피너 개발

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/maindish/MainDishFragment.kt
- grid 방식, linear 방식 변경 가능
- default 상태는 grid 방식
=> [FEAT] #29 든든한 메인요리 화면 선택한 버튼에 따라 리스트 나타내는 방식 변경

app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/CartDao.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/CartRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllCartInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetSoupDishesUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertCartInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/IsExistCartInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/BindingAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiCartState.kt, app/src/main/res/drawable/btn_cart_inserted_32dp.xml, app/src/main/res/drawable/ic_check_white.xml, app/src/main/res/layout/item_soup.xml, app/src/main/res/values/dimens.xml
* insert 여부에 따라 장바구니 아이콘, 체크 아이콘 변경함
* insert 여부에 따라 elevation 수정
=> [FEAT] #38 장바구니 insert 여부 확인 로직 구현

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemsUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishGridAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt, app/src/main/res/layout/fragment_maindish.xml
- CreateUiDishItemsUseCase 수정
- UseCase에서 coroutineScope 블록 사용 & async 배치
=> [CHORE] 메인 요리 UseCase 수정

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateEmptyUiDishItemUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemsUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetCartInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/CartBottomSheetFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/CartBottomSheetViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishGridAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt, app/src/main/res/layout/fragment_cart_bottom_sheet.xml, app/src/main/res/layout/fragment_maindish.xml
- 현재 선택한 상품 정보 뷰모델에서 관리
-  +, - 버튼으로 수량 변경 기능
-  변경된 수량에 따라 총 가격 변하도록 구현
=> [FEAT] Cart Bottom Sheet 수량 변경 기능

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemsUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiExhibitionItemsUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemListUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt
- List < DishItem > 을 받아 List < UiDishItem > 형태로 반환하는 유스케이스 작성
=> [CHORE] 기획전, 메인요리 리스트 불러오는데 사용되는 UseCase 수정

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/CartDialogFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/CartDialogFragmentViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/res/layout/fragment_cart_dialog.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
- 실패 시 : 토스트 메시지 나타나고 그대로
- 성공 시 : Bottom Sheet 사라지고 Dialog 나타남
=> [FEAT] Bottom Sheet에서 장바구니 작업 성공 시 Dialog 나타나도록 구현

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDishItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt, app/src/main/res/layout/fragment_cart_dialog.xml
* viewmodel 단에서 업데이트된 item의 hash값을 이용하여 list 갱신
=> [FEAT] 장바구니 insert시 cart icon 주황색으로 update

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/CartDialogFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/CartDialogFragmentViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt, app/src/main/res/layout/fragment_cart_dialog.xml
- 장바구니 확인, 계속 쇼핑하기 선택 시 이벤트 감지할 수 있도록 세팅
- 현재 메인 요리만 세팅해둠
=> [FEAT] Cart Dialog 이벤트 설정 (메인 요리)

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemsUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemListUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemUseCase.kt, app/src/main/res/layout/item_exhibition_horizontal.xml, app/src/main/res/layout/item_maindish_linear.xml
- 아이템 리스트 불러오면서 장바구니 포함 여부도 같이 체크하도록 수정
=> [CHORE] 기획전, 메인 요리 UseCase 수정

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishDetailRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDetailInfo.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateEmptyUiDetailInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDetailInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailContentAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailSectionImageAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailThumbImageAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailThumbViewPagerAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionHorizontalAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/DetailUiState.kt, app/src/main/res/layout/activity_detail.xml, app/src/main/res/layout/fragment_cart_bottom_sheet.xml, app/src/main/res/layout/item_detail_content.xml, app/src/main/res/layout/item_detail_section_image.xml, app/src/main/res/layout/item_detail_thumb_image.xml, app/src/main/res/layout/item_detail_thumb_image_rv.xml, buildSrc/src/main/kotlin/woowahan/android10/deliverbanchan/Dependencies.kt
- ConcatAdapter 사용
- 상단 뷰페이저 영역, 상품 정보 영역, 하단 상품 이미지 리스트 영역
- todo : 뷰페이저 인디케이터 구현하기, 수량 변경 기능
=> [FEAT] 상세 화면 데이터 나타내기

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDetailInfo.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDetailInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailContentAdapter.kt, app/src/main/res/layout/item_detail_content.xml
-  +, - 버튼 클릭 시 뷰모델의 데이터 변경
- 변경된 데이터 감지 후 상세화면에서 상품 정보를 나타내는 부분의 어댑터에서 다시 submitList
- 변경된 수량에 따라 총 주문금액 같이 변경되도록 구현
=> [FEAT] 상세화면 수량 변경 및 총 주문금액 변경 기능

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailThumbImageAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailThumbViewPagerAdapter.kt, app/src/main/res/drawable/tab_indicator_background_selector.xml, app/src/main/res/drawable/tab_indicator_selected_background.xml, app/src/main/res/drawable/tab_indicator_unselected_background.xml, app/src/main/res/layout/item_detail_thumb_image_rv.xml, app/src/main/res/layout/tab_indicator.xml
- 이미지 개수에 맞춰서 indicator 생성
- tab layout 을 활용
=> [FEAT] 상품 상세화면 상단 이미지 뷰페이저 indicator 구현

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/common/MainGridAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishLinearAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt
국물, 반찬 화면 Bottom Sheet 으로 상품 담고 다이얼로그 까지 나타나도록 세팅
=> [FEAT] 국물, 반찬 기능 미적용 부분 추가하기

app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/join/Order.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/DishRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/OrderRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/RecentlyViewedRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/CartRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/DishRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/OrderRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/RecentlyViewedRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllRecentlyViewedInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetJoinUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/IsExistCartInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartDishTopBodyAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartRecentlyViewedFooterAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/common/GridItemDecorator.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recently/RecentlyViewedVerticalAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/BindingAdapter.kt, app/src/main/res/layout/item_cart_dish_top_body.xml, app/src/main/res/layout/item_cart_recently_viewed_footer.xml, app/src/main/res/layout/item_recently_viewed.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> [FEAT] #72 카트 콘캣 어댑터 화면 개발

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/adapter/DetailContentAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionHorizontalAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishLinearAdapter.kt
- 상세 화면 버튼 누를 시 원하는 동작 처리할 수 있도록 추가
=> [FEAT] 상세 화면 버튼 이벤트 세팅

app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/CartDao.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/DishRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/OrderRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/RecentlyViewedRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiCartJoinItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/CartRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/DeleteCartInfoByHashUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/UpdateCartAmount.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/UpdateCartChecked.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartDishTopBodyAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartRecentlyViewedFooterAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartSelectHeaderAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetViewModel.kt, app/src/main/res/layout/item_cart_dish_top_body.xml
* 현재 개발한 adapter interface view 
* +, -, 삭제 view 터치시 이벤트 정의
=> [FEAT]/cart adapter interface

app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartDishTopBodyAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/adapter/CartSelectHeaderAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/model/UiCartBottomBody.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/BindingAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/IntExtention.kt, app/src/main/res/layout/item_cart_order_info_bottom_body.xml, app/src/main/res/layout/item_cart_recently_viewed_footer.xml, app/src/main/res/values/strings.xml
* Todo -> 전체 선택 및 해제 -> 선택 삭제
* Todo -> Order 진행 및 Cart 삭제 작업
* Todo -> 전체보기 눌렀을때 페이징 리스트 띄워주기
=> [FEAT] 카트화면 수량, 체크 상태에 따른 가격 및 버튼 상태 동기화

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiOrderListItem.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/OrderListVerticalDecoration.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt
- 주문 리스트 리사이클러뷰에 사용할 도메인 클래스 추가
- 마지막 아이템은 bottom 간격 생기도록 ItemDecoration 클래스 수정
=> [CHORE] 주문 리스트 리사이클러뷰 데이터 클래스 및 간격 수정

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiOrderInfo.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/BindingAdapterOrder.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderDetailAdapter.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderDetailFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderInfoAdapter.kt, app/src/main/res/layout/fragment_order_detail.xml, app/src/main/res/layout/item_order_detail.xml, app/src/main/res/layout/item_order_info.xml, app/src/main/res/values/strings.xml
- 선택한 주문 리스트에 포함된 상품들 나타내기
- 상품 총 가격, 배송료, 둘을 합한 총가격 나타내기
- todo : 배송 중인 경우 시간 체크
=> [FEAT] 주문 상세 페이지 (주문 리스트에서 아이템 하나 선택 시 이동)

.idea/deploymentTargetDropDown.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/GlobalApplication.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/background/LocalDBWorker.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt, build.gradle, buildSrc/src/main/kotlin/woowahan/android10/deliverbanchan/Dependencies.kt
- CoroutineWorker 사용
- 리스트를 넘기는 과정에서 리스트를 String 으로 변환하고 다시 리스트로 변환하는 과정 거침
=> [FIX] CoroutineWorker로 Cart DB 업데이트 할 수 있게 추가

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionViewModel.kt
=> [FIX] 기획전 카트 아이콘 감지 로직 수정

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/CartDialogFragment.kt
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
super.onCreate(savedInstanceState)
isCancelable = false
}
```
- 다이얼로그 프래그먼트에 위와 같이 추가
=> [FIX] 다이얼로그 외부 터치 시 사라지지 않게 수정

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt, app/src/main/res/layout/fragment_maindish.xml
- 메인 요리 화면 정렬 스피너 추가
- 현재 = 그리드 -> 리니어 변경 시 정렬 상태 유지
=> [FEAT] 메인 요리 화면 정렬 스피너 추가

app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/RecentViewedDao.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/RecentViewedRepositoryImpl.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/RecentViewedRepository.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllRecentJoinPagerUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetJoinUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/res/layout/item_recent_viewed.xml
* 유즈케이스단에서 뷰모델로 내려줄때, 세일퍼센트를 계산하지 않아서 생긴 오류 수정
* 최근 확인한 리스트 Limit 7 query 함수 네이밍 수정
=> [FIX] 리센트 페이징 리스트 받을때 세일퍼센트 계산하지 않은것 수정

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/NumberDialogFragment.kt
* 넘버피커 최솟값 0으로 되어있어서 1로 수정함
* 가격 합계 구할때 forEach대신 fold함수 사용
=> [FIX] 넘버피커 최솟값 1로 수정 및 코틀린 fold 함수 사용

app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllCartInfoUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllOrderInfoListUseCase.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiLocalState.kt, app/src/main/res/layout/activity_detail.xml, app/src/main/res/layout/layout_app_bar_no_back_btn.xml
* 디테일 액티비티 앱바 만들기
* 로컬디비 플로우를 받아와서 아이콘 갱신
* 장바구니에 없었던것 insert 후 디테일 액티비티에서 재 인서트시 기존에 있는 수량에 추가하는것으로 변경
* 로딩시 프로그레스바 개발
=> [FEAT] 디테일 액티비티 앱바, 로딩, 플로우 데이터 연동

app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/decorator/GridSpanCountTwoForMainDishDecorator.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/res/layout/fragment_maindish.xml, app/src/main/res/layout/item_maindish_linear.xml
- 리사이클러뷰 간격 수정
- 그리드용 데코레이션 클래스 추가
=> [FIX] 메인 요리 화면 리스트 간격 수정

app/src/main/res/layout/item_maindish_linear.xml
=> [FIX] 메인 화면 리니어 리스트 상품 설명 텍스트뷰 수정

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/ext/ListAdapterExtension.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt, app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
- RecyclerView.AdapterDataObserver 사용
- callbackFlow 를 통해 이벤트 전달
=> [FIX] 메인, 국물, 반찬 리스트 sorting 후 스크롤 내려가는 현상 해결 방법 수정
